version: "3.8"

services:

  development-db:
    container_name: dev_db_cafe
    restart: always
    image: postgres:15.1
    volumes:
      - development-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: dev_cafe        
      POSTGRES_PASSWORD: cafecafe
      POSTGRES_DB: cafe_db  


volumes:
  development-data:
    external: false
